### ISSUE TITLE
[copyright infringement] please rename your packages and organisation on github

### ISSUE THREAD

**Issue by nicolas-grekas** [symfonyboot/optional#1]
Hello,

Naming your organization and your packages symfonyboot is going to create confusion for the community.

Also Symfony is a trademark that must be used within the policy described at https://symfony.com/trademark

Please rename your organization and all related packages.

Thanks for your understanding.

**Comment by silasyudi** [comment]
Hi Nicolas, I sent this project to my personal namespace to fix this copyright issue. Thank you for the patience.
